input:
  cockroachdb_changefeed:
    dsn: postgresql://root@localhost:26257/defaultdb?sslmode=disable
    tables: [ posts, comments ]
    cursor_cache: cursor_cache

pipeline:
  processors:
    # {
    #   "primary_key": "[\"1a7ff641-3e3b-47ee-94fe-a0cadb56cd8f\", 2]",
    #   "row": "{\"after\": {\"k\": \"1a7ff641-3e3b-47ee-94fe-a0cadb56cd8f\", \"v\": 2}, \"updated\": \"1637953249519902405.0000000000\"}",
    #   "table": "strm_2"
    # }
    - mapping: |
        root = this.row.parse_json().after
        root.type = this.table.trim_suffix("s")

    - branch:
        request_map: |
          root = if this.type == "comment" {
            this.post
          } else {
            deleted()
          }
        processors:
          - sql_select:
              driver: postgres
              dsn: postgresql://root@localhost:26257/defaultdb?sslmode=disable
              table: posts
              columns: [ content, author ]
              where: id = $1
              args_mapping: '[ content().string() ]'
        result_map: |
          root.post = deleted()
          root.post.content = this.0.content
          root.post.author = this.0.author

output:
  nats:
    urls:
      - nats://localhost:4222
    subject: feed.${! this.type }

cache_resources:
  - label: cursor_cache
    file:
      directory: .
